### ISSUE TITLE
Tabs not loading

### ISSUE THREAD

**Issue by c3r63ru5** [fkoester/docker-kimai#1]
Installation process went smooth, I can login but none of the tabs are showing.
The Kimai and Apache logs are clean, it seems that the extensions are just not loaded at all.
Looks like a PHP issue for me but I have tried setting up an image based on PHP7 and with exactly the same problem.

**Comment by fkoester** [comment]
Strange, I don't have any issues like that. Which web browser do you use? Maybe some setting or browser addon prevents the tabs from showing?

**Comment by c3r63ru5** [comment]
Safari and Firefox, but ita related on how kimai.php is interpreted on the server, I don't think its a browser issue. The instance is using external mysql and is behind haproxy but this should not make much of a difference?

**Comment by fkoester** [comment]
What do the browsers log (F12) when accessing the page? Does it load all ressources with status 200 (network tab)?

**Comment by c3r63ru5** [comment]
Everything loads just fine, just one of the first js function calls ts_ext_onload can't be found. I checked and it should be references in kimai.php but the header section contains no references to js files as it should. This is because when this page is delivered, it first checks the extensions dir and iterates through all configs and init scripts, for some reason it does not load a single one.

I don't have access atm but can attach the snippet later today.

**Comment by c3r63ru5** [comment]
OK, so... kimai.php does not contain the references to the extension scripts as seen in other installations. I tried again with a fresh compose file and not using my existing MariaDB and it worked so it seems the problem is not related to your image/docker-compose files...

I really don't understand how this could be related to the used database but I think this issue can be closed.

Thanks.
